### PR TITLE
bGeigie from scratch

### PR DESCRIPTION
**Pull request by fakufaku**
I open this PR so that everyone can comment on the new concept.

### CODE REVIEW

**Comment by robouden** [comment]
Seems good start. I would like to see from the start an Arduino based development if possible. Not for myself, but for other developers/users.

**Comment by fakufaku** [comment]
@robouden What do you mean arduino based ? Is it the directory structure ?
The current plan is to make it modular enough that the hardware parts could be replaced by simulation and the whole firmware run on a laptop. This would be good for testing very peculiar bugs (like the GPS date wrap bug).

**Comment by Claypuppet** [comment]
@fakufaku The code looks good, but I think it's a good idea to also work towards something that you can at least compile or even upload (even if its empty setup/loop). This way we can setup our development environment for both development and testing/simulation. Another thing, it would do good to focus more on the design for now, like we did last Thursday, and get the infrastructure and flow in some diagrams. Makes it easier to discuss ideas and issues.

We could merge this and change the code / designs as we go along :)

**Comment by robouden** [comment]
Agree with Jelle.

**Comment by fakufaku** [comment]
Sounds good. What I have should not be too far from compiling on ESP32, so I'll try that and push then.

**Pull request merged**
